name: Processar Posts do Fórum
on:
  workflow_dispatch: # Permite acionar manualmente
  repository_dispatch: # Para acionar via API

jobs:
  process_post:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar post para Discussions
        env:
          GITHUB_TOKEN: ${{ secrets.FORUM_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/discussions \
            -d '{"title":"Novo post via Action", "body":"${{ github.event.client_payload.message }}", "category":"General"}'
