name: Publicar comentário no fórum

on:
  push:
    paths:
      - comentarios/entrada.txt

jobs:
  comentar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Ler conteúdo
        id: mensagem
        run: |
          BODY=$(cat comentarios/entrada.txt)
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comentar na Discussão
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/ops-era-phishing/Membrana/discussions/DISCUSSION_ID/comments \
            -d "{\"body\": \"${{ steps.mensagem.outputs.body }}\"}"
