name: Atualizar Fórum MEMBRANA

on:
  schedule:
    - cron: '*/30 * * * *'  # a cada 30 min
  workflow_dispatch:

jobs:
  update-forum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install graphql-request

      - name: Executar script de fetch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node src/fetch-discussions.js

      - name: Commit e push do JSON
        run: |
          git config user.name "MembranaBot"
          git config user.email "membrana@bot.com"
          git add public/forum.json
          git commit -m "🤖 Atualização automática do fórum"
          git push
